[project]
name = "proj-draft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "groq>=1.0.0",
    "langchain>=1.2.0",
    "langchain-text-splitters>=1.1.0",
    "sentence-transformers>=5.2.0",
]
